apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"skupper-network-observer"}}'
  labels:
    app.kubernetes.io/instance: skupper-network-observer
    app.kubernetes.io/name: network-observer
    app.kubernetes.io/part-of: skupper-network-observer
    app.kubernetes.io/version: 2.0.1
  name: skupper-network-observer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-succeeded
  labels:
    app.kubernetes.io/instance: skupper-network-observer
    app.kubernetes.io/name: network-observer
    app.kubernetes.io/part-of: skupper-network-observer
    app.kubernetes.io/version: 2.0.1
  name: skupper-network-observer-setup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-succeeded
  labels:
    app.kubernetes.io/instance: skupper-network-observer
    app.kubernetes.io/name: network-observer
    app.kubernetes.io/part-of: skupper-network-observer
    app.kubernetes.io/version: 2.0.1
  name: skupper-network-observer-setup
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-succeeded
  labels:
    app.kubernetes.io/instance: skupper-network-observer
    app.kubernetes.io/name: network-observer
    app.kubernetes.io/part-of: skupper-network-observer
    app.kubernetes.io/version: 2.0.1
  name: skupper-network-observer-setup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: skupper-network-observer-setup
subjects:
- kind: ServiceAccount
  name: skupper-network-observer-setup
---
apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
    scrape_configs:
      - job_name: "network-observer-local"
        scheme: http
        follow_redirects: true
        enable_http2: true
        static_configs:
          - targets: [ "localhost:8080" ]
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: skupper-network-observer
    app.kubernetes.io/name: network-observer
    app.kubernetes.io/part-of: skupper-network-observer
    app.kubernetes.io/version: 2.0.1
  name: skupper-network-observer-prometheus
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: skupper-network-observer-tls
  labels:
    app.kubernetes.io/instance: skupper-network-observer
    app.kubernetes.io/name: network-observer
    app.kubernetes.io/part-of: skupper-network-observer
    app.kubernetes.io/version: 2.0.1
  name: skupper-network-observer
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/instance: skupper-network-observer
    app.kubernetes.io/name: network-observer
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: skupper-network-observer
    app.kubernetes.io/name: network-observer
    app.kubernetes.io/part-of: skupper-network-observer
    app.kubernetes.io/version: 2.0.1
  name: skupper-network-observer
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: skupper-network-observer
      app.kubernetes.io/name: network-observer
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: skupper-network-observer
        app.kubernetes.io/name: network-observer
        app.kubernetes.io/part-of: skupper-network-observer
        app.kubernetes.io/version: 2.0.1
    spec:
      containers:
      - args:
        - -listen=127.0.0.1:8080
        - -prometheus-api=http://127.0.0.1:9090
        - -router-endpoint=amqps://skupper-router-local
        - -router-tls-ca=/etc/messaging/ca.crt
        - -router-tls-cert=/etc/messaging/tls.crt
        - -router-tls-key=/etc/messaging/tls.key
        image: registry.redhat.io/service-interconnect/skupper-network-observer-rhel9@sha256:498b5bb648e5bbaad07663941600173abac7d60a10744305f619509ddf7563e0
        imagePullPolicy: Always
        name: network-observer
        ports:
        - containerPort: 8080
          name: api
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /etc/messaging/
          name: skupper-management-client
      - args:
        - --config.file=/etc/prometheus/prometheus.yml
        - --storage.tsdb.path=/prometheus/
        image: registry.redhat.io/openshift4/ose-prometheus-rhel9@sha256:bd3f72544841c91c2d573a65ac3c988756f3523e17e0988027793b0f5f3ec3d1
        imagePullPolicy: IfNotPresent
        name: prometheus
        ports:
        - containerPort: 9090
          name: prom
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /etc/prometheus
          name: prometheus-config
        - mountPath: /prometheus
          name: prometheus-storage-volume
      - args:
        - --https-address=:8443
        - --provider=openshift
        - --openshift-service-account=skupper-network-observer
        - --upstream=http://127.0.0.1:8080
        - -tls-cert=/etc/certificates/tls.crt
        - -tls-key=/etc/certificates/tls.key
        - -cookie-secret-file=/etc/session-secrets/secret
        image: registry.redhat.io/openshift4/ose-oauth-proxy-rhel9@sha256:92f44cff160874efe57a985609e599b13c49c0c4cef846dccc80833af2ae74f3
        imagePullPolicy: IfNotPresent
        name: proxy
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /etc/certificates/
          name: skupper-network-observer-tls
        - mountPath: /etc/session-secrets/
          name: session-cookie-secret
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: skupper-network-observer
      volumes:
      - configMap:
          defaultMode: 420
          name: skupper-network-observer-prometheus
        name: prometheus-config
      - emptyDir: {}
        name: prometheus-storage-volume
      - name: skupper-management-client
        secret:
          defaultMode: 420
          secretName: skupper-network-observer-client
      - name: skupper-network-observer-tls
        secret:
          defaultMode: 420
          secretName: skupper-network-observer-tls
      - name: session-cookie-secret
        secret:
          defaultMode: 420
          secretName: skupper-network-observer-session
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-succeeded
  labels:
    app.kubernetes.io/instance: skupper-network-observer
    app.kubernetes.io/name: network-observer
    app.kubernetes.io/part-of: skupper-network-observer
    app.kubernetes.io/version: 2.0.1
  name: skupper-network-observer-setup
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: skupper-network-observer
        app.kubernetes.io/name: network-observer
        app.kubernetes.io/part-of: skupper-network-observer
        app.kubernetes.io/version: 2.0.1
      name: skupper-network-observer
    spec:
      containers:
      - args:
        - ensure-secret
        - -format=oauth2-proxy-session-cookie
        - skupper-network-observer-session
        image: registry.redhat.io/service-interconnect/skupper-network-observer-rhel9@sha256:498b5bb648e5bbaad07663941600173abac7d60a10744305f619509ddf7563e0
        name: init-session-cookie
      restartPolicy: Never
      serviceAccountName: skupper-network-observer-setup
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: skupper-network-observer
    app.kubernetes.io/name: network-observer
    app.kubernetes.io/part-of: skupper-network-observer
    app.kubernetes.io/version: 2.0.1
  name: skupper-network-observer
spec:
  port:
    targetPort: https
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: reencrypt
  to:
    kind: Service
    name: skupper-network-observer
    weight: 100
---
apiVersion: skupper.io/v2alpha1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/instance: skupper-network-observer
    app.kubernetes.io/name: network-observer
    app.kubernetes.io/part-of: skupper-network-observer
    app.kubernetes.io/version: 2.0.1
  name: skupper-network-observer-client
spec:
  ca: skupper-local-ca
  client: true
  hosts:
  - skupper-router-local
  subject: skupper-router-local
