apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: database

resources:
  - 00-namespace.yaml
  - 01-petclinicdb-pvc.yaml
  - 02-petclinicdb-secret.yaml
  - 03-petclinicdb-deployment.yaml
